More move calendar changes - can now move content
Chack JAVA_HOME early in some scripts

diff --git a/build/quickstart/linux/addgroupmember b/build/quickstart/linux/addgroupmember
--- a/build/quickstart/linux/addgroupmember
+++ b/build/quickstart/linux/addgroupmember
@@ -5,6 +5,13 @@
 # it can live within the svn repository.
 #
 
+if [ -z "$JAVA_HOME" -o ! -d "$JAVA_HOME" ] ; then
+  echo "*******************************************************"
+  echo "Error: JAVA_HOME is not defined correctly for Bedework."
+  echo "*******************************************************"
+  exit 1
+fi
+
 ANT_HOME=`dirname "$PRG"`/apache-ant-1.7.0
 ANT_HOME=`cd "$ANT_HOME" && pwd`
 
@@ -40,13 +47,6 @@ fi
 
 if [ "$group" = "" -o "$groupmember" = "" ] ; then
   errorUsage "Must supply group name and group member"
-fi
-
-if [ -z "$JAVA_HOME" -o ! -d "$JAVA_HOME" ] ; then
-  echo "*******************************************************"
-  echo "Error: JAVA_HOME is not defined correctly for Bedework."
-  echo "*******************************************************"
-  exit 1
 fi
 
 CLASSPATH=$ANT_HOME/lib/ant-launcher.jar
diff --git a/build/quickstart/linux/adduser b/build/quickstart/linux/adduser
--- a/build/quickstart/linux/adduser
+++ b/build/quickstart/linux/adduser
@@ -5,6 +5,13 @@
 # within the svn repository.
 #
 
+if [ -z "$JAVA_HOME" -o ! -d "$JAVA_HOME" ] ; then
+  echo "*******************************************************"
+  echo "Error: JAVA_HOME is not defined correctly for Bedework."
+  echo "*******************************************************"
+  exit 1
+fi
+
 ANT_HOME=`dirname "$PRG"`/apache-ant-1.7.0
 ANT_HOME=`cd "$ANT_HOME" && pwd`
 
@@ -76,13 +83,6 @@ do
     password=npassword
   fi
 done
-
-if [ -z "$JAVA_HOME" -o ! -d "$JAVA_HOME" ] ; then
-  echo "*******************************************************"
-  echo "Error: JAVA_HOME is not defined correctly for Bedework."
-  echo "*******************************************************"
-  exit 1
-fi
 
 ANT_CLASSPATH=$ANT_HOME/lib/ant-launcher.jar
 
diff --git a/build/quickstart/linux/initdir b/build/quickstart/linux/initdir
--- a/build/quickstart/linux/initdir
+++ b/build/quickstart/linux/initdir
@@ -5,6 +5,18 @@
 # within the svn repository.
 #
 
+errorUsage() {
+  echo "*******************************************************"
+  echo "Error: $1"
+  echo "*******************************************************"
+  usage
+  exit 1
+}
+
+if [ -z "$JAVA_HOME" -o ! -d "$JAVA_HOME" ] ; then
+  errorUsage "JAVA_HOME is not defined correctly for Bedework."
+fi
+
 ANT_HOME=`dirname "$PRG"`/apache-ant-1.7.0
 ANT_HOME=`cd "$ANT_HOME" && pwd`
 
@@ -16,21 +28,9 @@ usage() {
   echo ""
 }
 
-errorUsage() {
-  echo "*******************************************************"
-  echo "Error: $1"
-  echo "*******************************************************"
-  usage
-  exit 1
-}
-
 saveddir=`pwd`
 
 export QUICKSTART_HOME=$saveddir
-
-if [ -z "$JAVA_HOME" -o ! -d "$JAVA_HOME" ] ; then
-  errorUsage "JAVA_HOME is not defined correctly for Bedework."
-fi
 
 CLASSPATH=$ANT_HOME/lib/ant-launcher.jar
 
